helmDefaults:
  wait: true
  atomic: true
  verify: false # necessary as this is a local chart
  timeout: 30

environments:
  local: {}
  development: {}

releases:
- name: app
  namespace: service-intesis-v1
  createNamespace: true
  chart: ../helm/charts/service-intesis
  missingFileHandler: Warn
  values:
  - ../helm/values/app/{{ .Environment.Name }}.yaml
