name: Merge to Main
on:
  workflow_dispatch: {}
  push:
    branches:
    - 'main'
jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup buildx
      uses: docker/setup-buildx-action@v2
    - name: registry login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: |
          ghcr.io/${{ github.repository }}
    - id: release
      uses: rymndhng/release-on-push-action@v0.23.1
      with:
        bump_version_scheme: minor
        tag_prefix: v
    - name: package
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: ${{ steps.release.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/arm64,linux/arm/7
