name: Push to Main
on:
  workflow_dispatch: {}
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup buildx
      uses: docker/setup-buildx-action@v2
    - name: registry login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: semantic version
      uses: go-semantic-release/action@v1
      id: semver
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allow-initial-development-versions: true
        force-bump-patch-version: true
    - name: extract metadata (tags, labels) for docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
          type=raw,value=v${{ steps.semver.outputs.version }}
    - name: package
      uses: docker/bake-action@v2
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        push: true
        targets: release
